/// Flutter icons Ikonate
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ikonate
///      fonts:
///       - asset: fonts/Ikonate.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class Ikonate {
  Ikonate._();

  static const _kFontFam = 'Ikonate';

  static const IconData person_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData play_circled2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home_2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData hamburger = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData music_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData calendar_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData tv = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData basket = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData info_circled = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData comment_1 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData comment_alt = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData horn = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData sound = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData ticket_1 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData location_1 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData bookmark_empty = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData radio = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData ellypsis_vertical = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData bin = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData envelope2 = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData favourite = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData turn_right = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData back_left = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData back_right = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData chat_alt = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData signal = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData restaurant = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData explore = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData bookmark_1 = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData dolar = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData signal_alt = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData share_android = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData gruid = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData mail_alt = const IconData(0xf0e0, fontFamily: _kFontFam);
  static const IconData bell_alt = const IconData(0xf0f3, fontFamily: _kFontFam);
  static const IconData angle_left = const IconData(0xf104, fontFamily: _kFontFam);
  static const IconData angle_right = const IconData(0xf105, fontFamily: _kFontFam);
  static const IconData angle_up = const IconData(0xf106, fontFamily: _kFontFam);
  static const IconData angle_down = const IconData(0xf107, fontFamily: _kFontFam);
  static const IconData calendar_empty = const IconData(0xf133, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf1d8, fontFamily: _kFontFam);
  static const IconData paper_plane_empty = const IconData(0xf1d9, fontFamily: _kFontFam);
  static const IconData sliders = const IconData(0xf1de, fontFamily: _kFontFam);
  static const IconData cup = const IconData(0xf1e3, fontFamily: _kFontFam);
}
